<?php

namespace AppBundle\Repository;

/**
 * QuoteAPIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteAPIRepository extends \Doctrine\ORM\EntityRepository
{
}
